//****************************************************
// Funciones Consulta Campañas
//****************************************************
function cargaListadoCampañas() {

    // $('#tblListadoCampañas tr:not(:first)').remove();  Modificar funcion para no eliminar las 2 primeras filas de la tabla
    limpiarTabla("tblListadoCampañas", 1)

    if ($('#cboSegmento').val() == '0') {
        $('#tblListadoCampañas').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:5%"><label class="labelBE2">Id Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:14%"><label class="labelBE2">Nombre Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Segmento</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Inicio</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Termino</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Responsable</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Estado</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 8%;"><label class="labelBE2">Ver</label></td></tr>');
        $('#tblListadoCampañas').append('<tr style=" order: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; height:40px;"><label class="labelBE2">0002</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Campaña Todos en Casa 2020</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Micro Empresas</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">01/04/2020</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">01/05/2020</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Jorge Rivera</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Vigente</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; "><a href="#"><img src="../../Content/Images/lupa2.png" class="icon-det" title="Ver Detalle Campaña" onclick="cargaDataTarifaCampana(2)"></a></td></tr>');
        $('#tblListadoCampañas').append('<tr style=" order: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; height:40px;"><label class="labelBE2">0004</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Campaña Solidaria 2020</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Micro Empresas</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">01/04/2020</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">01/05/2020</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Jorge Rivera</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Eliminada</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; "><a href="#"><img src="../../Content/Images/lupa2.png" class="icon-det" title="Ver Detalle Campaña" onclick="cargaDataTarifaCampana(4)"></a></td></tr>');
    }
    if ($('#cboSegmento').val() == '1') {
        $('#tblListadoCampañas').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:5%"><label class="labelBE2">Id Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:14%"><label class="labelBE2">Nombre Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Segmento</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Inicio</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Termino</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Responsable</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Estado</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 8%;"><label class="labelBE2">Ver</label></td></tr>');
        $('#tblListadoCampañas').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; height:40px;"><label class="labelBE2">0001</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Campaña Verano 2020</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Pequeñas Empresas</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">19/02/2020</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">19/03/2020</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Enrique Fuentes</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Caducada</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; "><a href="#"><img src="../../Content/Images/lupa2.png" class="icon-det" title="Ver Detalle Campaña" onclick="cargaDataTarifaCampana(1)"></a></td></tr>');
        $('#tblListadoCampañas').append('<tr style=" order: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; height:40px;"><label class="labelBE2">0003</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Campaña Vuelta a Clases 2020</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Pequeñas Empresas</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">20/03/2020</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">20/04/2020</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Enrique Fuentes</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Cancelada</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; "><a href="#"><img src="../../Content/Images/lupa2.png" class="icon-det" title="Ver Detalle Campaña" onclick="cargaDataTarifaCampana(3)"></a></td></tr>');
    }
    if ($('#cboSegmento').val() == '2') {
        $('#tblListadoCampañas').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:5%"><label class="labelBE2">Id Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:14%"><label class="labelBE2">Nombre Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Segmento</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Inicio</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Termino</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Responsable</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Estado</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 8%;"><label class="labelBE2">Ver</label></td></tr>');
    }
    if ($('#cboSegmento').val() == '3') {
        $('#tblListadoCampañas').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:5%"><label class="labelBE2">Id Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:14%"><label class="labelBE2">Nombre Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Segmento</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Inicio</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Termino</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Responsable</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Estado</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 8%;"><label class="labelBE2">Ver</label></td></tr>');
        $('#tblListadoCampañas').append('<tr style=" order: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; height:40px;"><label class="labelBE2">0005</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Campaña Fiestas Patrias 2020</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Grandes Empresas</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">05/09/2020</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">05/10/2020</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Sergio Sanchez</label></td><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Programada</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; "><a href="#"><img src="../../Content/Images/lupa2.png" class="icon-det" title="Ver Detalle Campaña" onclick="cargaDataTarifaCampana(5)"></a></td></tr>');
    }
    if ($('#cboSegmento').val() == '4') {
        $('#tblListadoCampañas').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:5%"><label class="labelBE2">Id Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:14%"><label class="labelBE2">Nombre Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Segmento</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Inicio</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Termino</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Responsable</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Estado</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 8%;"><label class="labelBE2">Ver</label></td></tr>');
    }
    if ($('#cboSegmento').val() == '5') {
        $('#tblListadoCampañas').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:5%"><label class="labelBE2">Id Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:14%"><label class="labelBE2">Nombre Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Segmento</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Inicio</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Termino</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Responsable</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Estado</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 8%;"><label class="labelBE2">Ver</label></td></tr>');
    }
    if ($('#cboSegmento').val() == '6') {
        $('#tblListadoCampañas').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:5%"><label class="labelBE2">Id Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:14%"><label class="labelBE2">Nombre Campaña</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Segmento</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Inicio</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:11%"><label class="labelBE2">Fecha Termino</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Responsable</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:12%"><label class="labelBE2">Estado</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 8%;"><label class="labelBE2">Ver</label></td></tr>');
    }
}

function nuevaCampaña() {
    window.location.href = '/Gestion/ComexIINuevaCampaña';
}

//****************************************************
// Funciones Tarifas de Campañas Detalle
//****************************************************
function armaDataTarifaCampana() {

    var seleccionID = GetSession("identificador")
    document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: #FF9D25" colspan="9"><label class="cabeceraBE2">Detalle Tramos</label></td></tr>';

    if (seleccionID == 1) {
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 15%;"><label class="labelBE2">Tramo</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Gasto OUR USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Gasto OUR Garantizado USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Gasto OUR Garantizado EUR</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Gasto Swift</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Comisión</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Comisión Prorroga</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 9%;"><label class="labelBE2">Spread Ejecutivo (%)</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">Fecha Vencimiento Spread Ejecutivo</label></td></tr>';
        document.getElementById("lblId").innerText = "0001";
        document.getElementById("lblNombre").innerText = "Campaña Verano 2020";
        document.getElementById("lblResponsable").innerText = "Enrique Fuentes";
        document.getElementById("lblSegmento").innerText = "Pequeñas Empresas";
        document.getElementById("lblEstado").innerText = "Caducada";
        document.getElementById("lblFecInicio").innerText = "19/02/2020";
        document.getElementById("lblFecFin").innerText = "19/03/2020";
        document.getElementById("cboTipoProducto").value = 2;
        document.getElementById("cboSegmento").setItem = 4;
        //financiamiento
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">1,500 - 2,000 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">25,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">100,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">105,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label ></td ><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">369,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">85,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">2,60</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">24/01/20120</label></td></tr>';
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">2,001 - 2,500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">35,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">225,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">230,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label ></td ><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">400,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">15,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">1,10</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">01/02/2020</label></td></tr>';
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">2,501 - 3,000 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">45,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">126,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">130,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label ></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">200,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">19,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,98</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">06/03/2020</label></td></tr>';
    }
    else if (seleccionID == 2) {
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Tramo</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR Garantizado USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR Garantizado EUR</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto Swift</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray;"><label class="labelBE2">Comisión</label></td></tr>';
        document.getElementById("lblId").innerText = "0002";
        document.getElementById("lblNombre").innerText = "Campaña Todos en Casa 2020";
        document.getElementById("lblResponsable").innerText = "Jorge Rivera";
        document.getElementById("lblSegmento").innerText = "Micro Empresas";
        document.getElementById("lblEstado").innerText = "Vigente";
        document.getElementById("lblFecInicio").innerText = "01/04/2020";
        document.getElementById("lblFecFin").innerText = "01/05/2020";
        document.getElementById("cboTipoProducto").selectedIndex = 0;
        document.getElementById("cboTipoProducto").disabled = true;
        document.getElementById("cboSegmento").selectedIndex = 0;
        document.getElementById("cboSegmento").disabled = true;
        document.getElementById("cboCanal").selectedIndex = 2;
        document.getElementById("cboCanal").disabled = true;

        document.getElementById("btnEliminar").disabled = true;
        document.getElementById("btnModificar").disabled = true;
        //odp al exterior
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">0 - 500</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">320,00</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">71,00</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">71,00</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">120,00</label></td></tr>';
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">501 - 1,000</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">180,00</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">96,00</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">96,00</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">25,00</label></td></tr>';
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">1,001 - 1,500</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">50,00</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">54,00</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">54,00</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">36,00</label></td></tr>';
    }
    else if (seleccionID == 3) {
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Tramo</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR Garantizado USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR Garantizado EUR</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto Swift</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray;"><label class="labelBE2">Comisión</label></td></tr>';
        document.getElementById("lblId").innerText = "0003";
        document.getElementById("lblNombre").innerText = "Campaña Vuelta a Clases 2020";
        document.getElementById("lblResponsable").innerText = "Jorge Rivera";
        document.getElementById("lblSegmento").innerText = "Pequeñas Empresas";
        document.getElementById("lblEstado").innerText = "Cancelada";
        document.getElementById("lblFecInicio").innerText = "20/03/2020";
        document.getElementById("lblFecFin").innerText = "20/04/2020";
        document.getElementById("cboTipoProducto").seleccionID = 3;
        document.getElementById("cboSegmento").seleccionID = 1;
        document.getElementById("btnCancelar").disabled = true;
        document.getElementById("btnEliminar").disabled = true;
        //otro financiamiento
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">4,000 - 4,500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">25,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">35,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">40,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">552,00 </label></td></tr>';
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">4,501 - 5,000 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">36,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">09,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">12,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">411,00 </label></td></tr>';
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">5,001 - 5,500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">79,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">10,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">13,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">695,00 </label></td></tr>';
    }
    else if (seleccionID == 4) {
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 15%;"><label class="labelBE2">Tramo</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Gasto OUR USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Gasto OUR Garantizado USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Gasto OUR Garantizado EUR</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Gasto Swift</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Comisión</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Comisión Prorroga</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 9%;"><label class="labelBE2">Spread Ejecutivo (%)</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">Fecha Vencimiento Spread Ejecutivo</label></td></tr>';

        document.getElementById("lblId").innerText = "0004";
        document.getElementById("lblNombre").innerText = "Campaña Solidaria 2020";
        document.getElementById("lblResponsable").innerText = "Jorge Rivera";
        document.getElementById("lblSegmento").innerText = "Micro Empresas";
        document.getElementById("lblEstado").innerText = "Eliminada";
        document.getElementById("lblFecInicio").innerText = "01/04/2020";
        document.getElementById("lblFecFin").innerText = "01/05/2020";
        document.getElementById("cboTipoProducto").seleccionID = 2;
        document.getElementById("cboSegmento").seleccionID = 2;
        document.getElementById("btnDetener").disabled = true;
        document.getElementById("btnExtender").disabled = true;
        document.getElementById("btnEliminar").disabled = true;
        document.getElementById("btnModificar").disabled = true;
        //financiamiento
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">0 - 500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">38,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">650,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">660,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label ></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">369,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">85,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,60</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">09/04/2020</label></td></tr>';
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">501 - 1,000 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">35,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">750,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">780,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label ></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">258,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">66,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">1,60</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">03/03/2020</label></td></tr>';
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">1,001 - 1,500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">25,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">900,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">950,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label ></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">125,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">22,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">3,28</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">02/09/2020</label></td></tr>';
    }
    else if (seleccionID == 5) {
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Tramo</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR Garantizado USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR Garantizado EUR</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto Swift</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray;"><label class="labelBE2">Comisión</label></td></tr>';
        document.getElementById("lblId").innerText = "0005";
        document.getElementById("lblNombre").innerText = "Campaña Fiestas Patrias 2020";
        document.getElementById("lblResponsable").innerText = "Sergio Sanchez";
        document.getElementById("lblSegmento").innerText = "Grandes Empresas";
        document.getElementById("lblEstado").innerText = "Programada";
        document.getElementById("lblFecInicio").innerText = "05/09/2020";
        document.getElementById("lblFecFin").innerText = "05/10/2020";
        document.getElementById("cboTipoProducto").seleccionID = 1;
        document.getElementById("cboSegmento").seleccionID = 4;
        //odp al exterior
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">2,000 - 2,500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">98,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">23,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">365,00 </label></td></tr>';
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">2,501 - 3,000 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">110,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">22,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">25,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">563,00 </label></td></tr>';
        document.getElementById("tblCampanaTarifa").insertRow(-1).innerHTML = '<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">3,001 - 3,500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">116,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">12,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">15,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">258,00 </label></td></tr>';
    }
}

function cargaDataTarifaCampana(IdCarga) {

    window.location.href = '/Gestion/ComexIITarifasCampañas';
    if (IdCarga == "1") {
        cargaDataCampana(1);
    }
    else if (IdCarga == "2") {
        cargaDataCampana(2);
    }
    else if (IdCarga == "3") {
        cargaDataCampana(3);
    }
    else if (IdCarga == "4") {
        cargaDataCampana(4);
    }
    else if (IdCarga == "5") {
        cargaDataCampana(5);
    }
}

function cargaDataCampana(id) {
    SetSession("identificador", id);
}

function detenerCampana() {
    var id = document.getElementById("lblId").innerText;
    alert("Detendra campaña ID: " + "'" + id + "'" + " ¿esta seguro?");
}

function extenderCampana() {
    var id = document.getElementById("lblId").innerText;
    alert("Extender campaña ID: " + "'" + id + "'" + " ¿esta seguro?");
}

function eliminarCampana() {
    var id = document.getElementById("lblId").innerText;
    alert("Eliminara campaña ID: " + "'" + id + "'" + " ¿esta seguro?");
    alert("Eliminara correctamente");
}

function modificarCampana() {
    var id = document.getElementById("lblId").innerText;
    alert("Modificara campaña ID: " + "'" + id + "'" + " ¿esta seguro?");
}


//****************************************************
// Funciones Nueva Campaña
//****************************************************

function grillaNuevaCampaña() {
    limpiarTabla("tblNuevaCamp", 0);
    if ($('#cboTipoProducto').val() == '0') {
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: #FF9D25" colspan="7"><label class="cabeceraBE2">Detalle Tramos</label></td></tr>');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Tramo</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR Garantizado USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR Garantizado EUR</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto Swift</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray;"><label class="labelBE2">Comisión</label></td></tr>');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="tram1" class="labelBE2">0 - 500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm1" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15"/>&nbsp;<label id = "lblMonOur1"class= "labelBE2" > </label ></td > <td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm2" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar1" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm2" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar1" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm3" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td></tr >');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="tram2" class="labelBE2">501 - 1,000 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm5" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15"/>&nbsp;<label id = "lblMonOur2" class= "labelBE2" > </label ></td > <td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm6" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar2" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm6" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar2" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm7" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm8" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td></tr >');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="tram3" class="labelBE2">1,001 - 1,500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm9" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15"/>&nbsp;<label id = "lblMonOur3" class= "labelBE2" > </label ></td > <td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm10" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar3" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm10" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar3" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm11" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm12" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td></tr >');
    }
    if ($('#cboTipoProducto').val() == '1') {
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: #FF9D25" colspan="10"><label class="cabeceraBE2">Detalle Tramos</label></td></tr>');
        $('#tblNuevaCamp').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Tramo</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR Garantizado USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR Garantizado EUR</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto Swift</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray;"><label class="labelBE2">Comisión</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray;"><label class="labelBE2">Comisión All-in</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:10%"><label class="labelBE2">Comisión Prorroga</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:8%"><label class="labelBE2">Spread Ejecutivo (%)</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:10%"><label class="labelBE2">Fecha Vencimiento Spread Ejecutivo</label></td></tr>');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="tram1" class="labelBE2">0 - 500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm1" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15"/>&nbsp;<label id="lblMonOur1" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm2" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar1" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm3" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm13" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> 23,00 </label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> 23,00   </label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> 2,50  </label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> -- </label></td></tr>');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="tram2" class="labelBE2">501 - 1,000 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm5" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15"/>&nbsp;<label id="lblMonOur2" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm6" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar2" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm7" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm8" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm14" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> 24,00 </label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> 24,00   </label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> 3,50  </label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> -- </label></td></tr>');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="tram3" class="labelBE2">1,001 - 1,500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm9" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15"/>&nbsp;<label id="lblMonOur3" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm10" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar3" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm11" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm12" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm15" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> 25,00 </label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> 25,00   </label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> 4,50  </label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> -- </label></td></tr>');
    }
    if ($('#cboTipoProducto').val() == '2') {
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: #FF9D25" colspan="5"><label class="cabeceraBE2">Detalle Tramos</label></td></tr>');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Tramo</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto OUR Garantizado</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto Swift</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray;"><label class="labelBE2">Comisión</label></td></tr>');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="tram1" class="labelBE2">0 - 500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm1" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15"/>&nbsp;<label id="lblMonOur1" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm2" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar1" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm3" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td></tr>');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="tram2" class="labelBE2">501 - 1,000 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm5" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15"/>&nbsp;<label id="lblMonOur2" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm6" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar2" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm7" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm8" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td></tr>');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="tram3" class="labelBE2">1,001 - 1,500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm9" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15"/>&nbsp;<label id="lblMonOur3" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm10" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar3" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm11" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm12" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td></tr>');
    }
    if ($('#cboTipoProducto').val() == '3') {
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: #FF9D25" colspan="11"><label class="cabeceraBE2">Detalle Tramos</label></td></tr>');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Tramo</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Comisión apertura</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Gasto Swift</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Comisión All-in</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray"><label class="labelBE2">Comisión de Modificación</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray;"><label class="labelBE2">Comisión de Anulación</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray;"><label class="labelBE2">Comisión Prorroga</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:10%"><label class="labelBE2">Tasa Apertura-Negociación</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:10%"><label class="labelBE2">Tasa Plazo Proveedor</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:8%"><label class="labelBE2">Spread Ejecutivo (%)</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width:10%"><label class="labelBE2">Fecha Vencimiento Spread Ejecutivo</label></td></tr>');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="tram1" class="labelBE2">0 - 500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm1" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15"/>&nbsp;<label id="lblMonOur1" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm2" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar1" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm3" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> -- </label></td></tr>');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="tram2" class="labelBE2">501 - 1,000 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm5" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15"/>&nbsp;<label id="lblMonOur2" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm6" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar2" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm7" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> -- </label></td></tr>');
        $("#tblNuevaCamp").append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="tram3" class="labelBE2">1,001 - 1,500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm9" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15"/>&nbsp;<label id="lblMonOur3" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm10" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label id="lblMonOurGar3" class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm11" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm12" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><input id="cm4" type="text" value="0,00" size="10" disabled style="text-align:right; width:80%" maxlength="15" />&nbsp;<label class="labelBE2"></label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2"> -- </label></td></tr>');
    }
}

function cambioMonedaNuevaCampaña() {

    if ($('#cboTipoMoneda').val() == '0') { // Dolar
        $("#tram1").html('0 - 500 ');
        $("#tram2").html('501 - 1,000 ');
        $("#tram3").html('1,001 - 1,500 ');

        $("#lblMonOur1").html('');
        $("#lblMonOur2").html('');
        $("#lblMonOur3").html('');

        $("#lblMonOurGar1").html('');
        $("#lblMonOurGar2").html('');
        $("#lblMonOurGar3").html('');
    }
    if ($('#cboTipoMoneda').val() == '1') { // Euro
        $("#tram1").html('0 - 500 ');
        $("#tram2").html('501 - 1,000 ');
        $("#tram3").html('1,001 - 1,500 ');

        $("#lblMonOur1").html('');
        $("#lblMonOur2").html('');
        $("#lblMonOur3").html('');

        $("#lblMonOurGar1").html('');
        $("#lblMonOurGar2").html('');
        $("#lblMonOurGar3").html('');
    }
    if ($('#cboTipoMoneda').val() == '2') {// Peso
        $("#tram1").html('000.000 - 1.000.000 ');
        $("#tram2").html('1.000.001 - 2.000.000 ');
        $("#tram3").html('2.000.001 - 3.000.000 ');

        $("#lblMonOur1").html('');
        $("#lblMonOur2").html('');
        $("#lblMonOur3").html('');

        $("#lblMonOurGar1").html('');
        $("#lblMonOurGar2").html('');
        $("#lblMonOurGar3").html('');
    }
}

function editaNuevaCampaña(id) {
    switch (id) {
        case 1:
            //$("#cm1").prop("disabled", false); $("#cm2").prop("disabled", false); $("#cm3").prop("disabled", false);
            //$("#cm4").prop("disabled", false); $("#cm5").prop("disabled", false); $("#cm6").prop("disabled", false);
            //$("#cm7").prop("disabled", false); $("#cm8").prop("disabled", false); $("#cm9").prop("disabled", false);
            //$("#cm10").prop("disabled", false); $("#cm11").prop("disabled", false); $("#cm12").prop("disabled", false);

            $("#tblNuevaCamp :input").prop("disabled", false);

            $("#btnEdita").prop("disabled", true);
            $("#btnGuardar").prop("disabled", false);
            break;
        case 2:
            //$("#cm1").prop("disabled", true); $("#cm2").prop("disabled", true); $("#cm3").prop("disabled", true);
            //$("#cm4").prop("disabled", true); $("#cm5").prop("disabled", true); $("#cm6").prop("disabled", true);
            //$("#cm7").prop("disabled", true); $("#cm8").prop("disabled", true); $("#cm9").prop("disabled", true);
            //$("#cm10").prop("disabled", true); $("#cm11").prop("disabled", true); $("#cm12").prop("disabled", true);

            $("#tblNuevaCamp :input").prop("disabled", true);

            $("#btnEdita").prop("disabled", false);
            $("#btnGuardar").prop("disabled", true);
            break;
    }
}