function consultaPrecios() {
    cargaGrillaTblPE();
    cargaGrillaTblMT();
}

function cargaGrillaTblPE() {
    $('#lblNoPreciosTC').show();

    var cabecera = ["Tramo", "Gasto OUR USD", "Gasto OUR Garantizado USD", "Gasto OUR Garantizado EUR", "Gasto Swift", "Comisión", "Fecha Vigencia"];
    //var nuevaCab = ["Tipo Producto", "Gasto OUR USD", "Gasto OUR Garantizado USD", "Gasto OUR Garantizado EUR", "Gasto Swift", "Comisión", "Comisión All-in", "Comisión Prorroga", "Comisión apertura", "Comisión de Modificación", "Comisión de Anulación", "Tasa Apertura-Negociación","Tasa plazo proveedor", "Spread Ejecutivo (%)","Fecha Vencimiento Spread Ejecutivo"];
    //var nuevaCabDos = ["Tipo Producto","Comisión", "Comisión de aviso", "Comisión Modificación", "Comisión Anulación", "Comisión Traspaso", "Comisión Revisión", "Comisión All in", "Courier", "Spread Ejecutivo", "Fecha vigencia spread", "Comisión Prorroga"];
    var nuevaCabInv = ["Gasto OUR USD", "Gasto OUR Garantizado USD", "Gasto OUR Garantizado EUR", "Gasto Swift", "Comisión", "Comisión All-in", "Comisión Prorroga", "Comisión Apertura", "Comisión de Modificación", "Comisión de Anulación", "Comisión de Aviso", "Comisión Traspaso", "Comisión Revisión", "Courier", "Tasa Apertura-Negociación (%)", "Tasa plazo proveedor (%)", "Spread Ejecutivo (%)", "Fecha Vencimiento Spread Ejecutivo"];
    var listProd = ["Financiamiento Contado", "Otro Financiamiento", "Carta de Creditos", "Cobranza Documentaria de Importación", "Cobranza Documentaria de Exportación", "Cartas de Crédito de Exportación NC", "Cobranza Documentaria de Exportación"];

    //Tabla Original de Productos
    $('#tblPreciosPE1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: #FF9D25" colspan="15"><label class="cabeceraBE2">ODP al Exterior</label></td></tr>');
    $('#tblPreciosPE1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 19%;"><label class="labelBE2">' + cabecera[0] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[1] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[2] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[3] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[4] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[5] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[6] + '</label></td></tr>');
    $('#tblPreciosPE1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">0 - 500</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">30,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">32,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">10,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">08/07/2020 </label></td></tr>');
    $('#tblPreciosPE1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">501 - 1,000</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">30,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">50,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">53,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">108,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">08/07/2020 </label></td></tr>');
    $('#tblPreciosPE1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">1,001 - 1,500</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">10,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">12,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">9,20 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">08/07/2020 </label></td></tr>');

    //$('#tblPreciosPE1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 19%;"><label class="labelBE2">' + cabecera[0] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[1] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[2] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[3] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[4] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[5] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[6] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[7] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">' + cabecera[8] +'</label></td></tr>');

    //Tabla Original de Productos con Estructuras Nuevas
    //$('#tblPreciosPE1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: #FF9D25" colspan="15"><label class="cabeceraBE2">Productos</label></td></tr>');
    //$('#tblPreciosPE1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[0] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[1] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[2] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[3] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[4] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[5] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[6] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[7] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[8] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[9] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[10] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[11] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[12] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[13] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCab[14] + '</label></td></tr>');
    //$('#tblPreciosPE1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">ODP al Exterior</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">30,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">32,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">10,00 </label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td></tr>');
    //$('#tblPreciosPE1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Financiamiento Contado</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">30,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">50,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">53,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">108,00 </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">23,00 </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">23,00 </label></td><td id="td4" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td5" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">2,50</label></td><td id="td6" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">21/05/2017</label></td></tr>');
    //$('#tblPreciosPE1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Otro Financiamiento</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">10,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">12,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">9,20 </label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td></tr>');
    //$('#tblPreciosPE1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Carta de Creditos</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">10,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">12,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">9,20 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">22,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">23,00 </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">24,00 </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">22,00 </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">21,00 </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">25,00 </label></td><td id="td5" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">2,50</label></td><td id="td6" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">21/05/2017</label></td></tr>');

    //Tabla Productos Nuevos
    //$('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: #FF9D25" colspan="12"><label class="cabeceraBE2">Productos</label></td></tr>');
    //$('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCabDos[0] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCabDos[1] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCabDos[2] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCabDos[3] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCabDos[4] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCabDos[5] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCabDos[6] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCabDos[7] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCabDos[8] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCabDos[9] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCabDos[10] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + nuevaCabDos[11] + '</label></td></tr>');
    //$('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Cobranza Documentaria de Importación</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td></tr>');
    //$('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Cobranza Documentaria de Exportación</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">30,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">9,20 </label></td><td id="td4" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td5" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td6" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td></tr>');
    //$('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Cartas de Crédito de Exportación NC</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">10,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">12,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">12,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">12,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">12,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">9,20 </label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td></tr>');
    //$('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">Cobranza Documentaria de Exportación</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">--</label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">2,50</label></td><td id="td5" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">21/05/2017</label></td><td id="td6" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">22,00 </label></td></tr>');

    //Tabla Productos Invertido
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: #FF9D25" colspan="12"><label class="cabeceraBE2">Productos</label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2"></label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + listProd[0] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + listProd[1] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + listProd[2] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + listProd[3] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + listProd[4] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + listProd[5] + '</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; "><label class="labelBE2">' + listProd[6] + '</label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[0] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">10,00      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[1] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">12,00      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[2] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">14,00      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">24,00      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[3] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">22,00      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">22,00      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">11,20      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[4] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">10,00      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">25,00      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">15,00      </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">15,00      </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[5] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00       </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00       </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00       </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[6] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">15,00      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">14,20      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">21,15      </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[7] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">14,20      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[8] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">14,20      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">11,50      </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[9] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">14,20      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">15,20      </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[10] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">13,10      </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[11] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">18,50      </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[12] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">16,10      </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[13] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">15,00      </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">15,30      </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[14] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">14,20      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[15] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">14,20      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[16] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">2,20       </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">17,20      </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">10,20      </label></td></tr>');
    $('#tblPreciosPE2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: left; border: 1px solid; border-color: darkgray"><label class="labelBE2">' + nuevaCabInv[17] + '</label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">15/05/2017 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">27/05/2017 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">    --     </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">13/05/2017 </label></td></tr>');

}

function cargaGrillaTblMT() {
    $('#tblPreciosMT1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: #FF9D25" colspan="8"><label class="cabeceraBE2">ODP al Exterior</label></td></tr>');
    $('#tblPreciosMT1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 17%;"><label class="labelBE2">Tramo</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 14%;"><label class="labelBE2">Gasto OUR USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 14%;"><label class="labelBE2">Gasto OUR Garantizado USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 14%;"><label class="labelBE2">Gasto OUR Garantizado EUR</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 14%;"><label class="labelBE2">Gasto Swift</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 14%;"><label class="labelBE2">Comisión</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 14%;"><label class="labelBE2">Fecha Vigencia</label></td></tr>');
    $('#tblPreciosMT1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="lblTramo11" class="labelBE2">0 - 500 </labe></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur11" class="labelBE2">25,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">25,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">27,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">08/07/2020 </label></td></tr>');
    $('#tblPreciosMT1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="lblTramo12" class="labelBE2">501 - 1,000 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur12" class="labelBE2">35,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar12" class="labelBE2">35,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">37,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">25,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">08/07/2020 </label></td></tr>');
    $('#tblPreciosMT1').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray"><label id="lblTramo13" class="labelBE2">1,001 - 1,500 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur13" class="labelBE2">45,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar13" class="labelBE2">45,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">47,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">30,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">08/07/2020 </label></td></tr>');

    $('#tblPreciosMT2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: #FF9D25" colspan="10"><label class="cabeceraBE2">Financiamiento Contado</label></td></tr>');
    $('#tblPreciosMT2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Gasto OUR USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Gasto OUR Garantizado USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Gasto OUR Garantizado EUR</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Gasto Swift</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Comisión</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Comisión All-in</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 11%;"><label class="labelBE2">Comisión Prorroga</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 9%;"><label class="labelBE2">Spread Ejecutivo (%)</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 10%;"><label class="labelBE2">Fecha Vencimiento Spread Ejecutivo</label></td></tr>');
    $('#tblPreciosMT2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur21" class="labelBE2">55,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar21" class="labelBE2">50,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">52,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">35,00 </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">23,00 </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">23,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">2,50</label></td><td id="td6" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">21/05/2017</label></td></tr>');
    $('#tblPreciosMT2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur22" class="labelBE2">60,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar22" class="labelBE2">80,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">82,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">40,00 </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">23,00 </label></td><td id="td7" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">24,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">3,50</label></td><td id="td9" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">12/08/2018</label></td></tr>');
    $('#tblPreciosMT2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur23" class="labelBE2">90,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar23" class="labelBE2">70,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">72,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">45,00 </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">23,00 </label></td><td id="td10" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">25,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">4,50</label></td><td id="td12" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">31/12/2019</label></td></tr>');
    $('#tblPreciosMT2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur24" class="labelBE2">50,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar24" class="labelBE2">80,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">82,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">55,00 </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">23,00 </label></td><td id="td10" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">36,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">4,50</label></td><td id="td12" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">31/12/2019</label></td></tr>');
    $('#tblPreciosMT2').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur25" class="labelBE2">100,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar25" class="labelBE2">90,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">92,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">65,00 </label></td><td id="td4" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">23,00 </label></td><td id="td10" style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">40,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">4,50</label></td><td id="td12" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">31/12/2019</label></td></tr>');

    $('#tblPreciosMT3').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: #FF9D25" colspan="8"><label class="cabeceraBE2">Otro Financiamiento</label></td></tr>');
    $('#tblPreciosMT3').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 14%;"><label class="labelBE2">Gasto OUR USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 14%;"><label class="labelBE2">Gasto OUR Garantizado USD</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 14%;"><label class="labelBE2">Gasto OUR Garantizado EUR</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 14%;"><label class="labelBE2">Gasto Swift</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 14%;"><label class="labelBE2">Comisión</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 14%;"><label class="labelBE2">Fecha Vigencia</label></td></tr>');
    $('#tblPreciosMT3').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur31" class="labelBE2">100,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar31" class="labelBE2">90,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">92,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">50,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">08/07/2020 </label></td></tr>');
    $('#tblPreciosMT3').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur32" class="labelBE2">195,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar32" class="labelBE2">95,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">97,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">55,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">08/07/2020 </label></td></tr>');
    $('#tblPreciosMT3').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur33" class="labelBE2">150,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar33" class="labelBE2">100,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">102,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">80,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">08/07/2020 </label></td></tr>');
    $('#tblPreciosMT3').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur34" class="labelBE2">10,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar34" class="labelBE2">105,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">107,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">90,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">08/07/2020 </label></td></tr>');

    $('#tblPreciosMT4').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: #FF9D25" colspan="11"><label class="cabeceraBE2">Carta de Creditos</label></td></tr>');
    $('#tblPreciosMT4').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 9%;"><label class="labelBE2">Comisión Apertura</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 9%;"><label class="labelBE2">Gasto Swift</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 9%;"><label class="labelBE2">Comisión All-in</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 9%;"><label class="labelBE2">Comisión de Modificación</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 9%;"><label class="labelBE2">Comisión de Anulación</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 9%;"><label class="labelBE2">Comisión Prorroga</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 8%;"><label class="labelBE2">Tasa Apertura-Negociación (%)</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 8%;"><label class="labelBE2">Tasa Plazo Proveedor (%)</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 8%;"><label class="labelBE2">Spread Ejecutivo (%)</label></td><td style="text-align: center; border: 1px solid; border-color: darkgray; background-color: lightgray; width: 8%;"><label class="labelBE2">Fecha Vencimiento Spread Ejecutivo</label></td></tr>');
    $('#tblPreciosMT4').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur11" class="labelBE2">25,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">25,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">27,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">2,50</label></td><td id="td6" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">21/05/2017</label></td></tr>');
    $('#tblPreciosMT4').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur12" class="labelBE2">35,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar12" class="labelBE2">35,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">37,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">25,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">2,50</label></td><td id="td6" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">21/05/2017</label></td></tr>');
    $('#tblPreciosMT4').append('<tr style="border: 1px solid; border-color: darkgray"><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOur13" class="labelBE2">45,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar13" class="labelBE2">45,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label id="lblMonOurGar11" class="labelBE2">47,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">0,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">20,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">30,00 </label></td><td style="text-align: right; border: 1px solid; border-color: darkgray"><label class="labelBE2">2,50</label></td><td id="td6" style="text-align: center; border: 1px solid; border-color: darkgray"><label class="labelBE2">21/05/2017</label></td></tr>');

}

function cambioMonedaPrecios() {

    if ($("#cboTipoMoneda").val() == "0") { // Moneda Dolar
        $('#lblTramo11').html('0 - 500 ');
        $('#lblTramo12').html('501 - 1,000 ');
        $('#lblTramo13').html('1,001 - 1,500 ');

        $('#lblMonOur11').html('25,00 ');
        $('#lblMonOur12').html('35,00 ');
        $('#lblMonOur13').html('45,00 ');

        $('#lblMonOurGar11').html('25,00 ');
        $('#lblMonOurGar12').html('35,00 ');
        $('#lblMonOurGar13').html('45,00 ');

        //TABLA 2
        $('#lblTramo21').html('0 - 500 ');
        $('#lblTramo22').html('501 - 1,000 ');
        $('#lblTramo23').html('1,001 - 1,500 ');
        $('#lblTramo24').html('1,501 - 2,000 ');
        $('#lblTramo25').html('2,001 - 2,500 ');

        $('#lblMonOur21').html('55,00 ');
        $('#lblMonOur22').html('60,00 ');
        $('#lblMonOur23').html('90,00 ');
        $('#lblMonOur24').html('50,00 ');
        $('#lblMonOur25').html('100,00 ');

        $('#lblMonOurGar21').html('50,00 ');
        $('#lblMonOurGar22').html('80,00 ');
        $('#lblMonOurGar23').html('70,00 ');
        $('#lblMonOurGar24').html('80,00 ');
        $('#lblMonOurGar25').html('90,00 ');


        //TABLA 3
        $('#lblTramo31').html('0 - 500 ');
        $('#lblTramo32').html('501 - 1,000 ');
        $('#lblTramo33').html('1,001 - 1,500 ');
        $('#lblTramo34').html('1,501 - 2,000 ');

        $('#lblMonOur31').html('100,00 ');
        $('#lblMonOur32').html('195,00 ');
        $('#lblMonOur33').html('150,00 ');
        $('#lblMonOur34').html('10,00 ');

        $('#lblMonOurGar31').html('90,00 ');
        $('#lblMonOurGar32').html('95,00 ');
        $('#lblMonOurGar33').html('100,00 ');
        $('#lblMonOurGar34').html('105,00 ');

    }

    if ($("#cboTipoMoneda").val() == "1") { // Moneda Euro
        $('#lblTramo11').html('0 - 500 ');
        $('#lblTramo12').html('501 - 1,000 ');
        $('#lblTramo13').html('1,001 - 1,500 ');

        $('#lblMonOur11').html('25,00 ');
        $('#lblMonOur12').html('35,00 ');
        $('#lblMonOur13').html('45,00 ');

        $('#lblMonOurGar11').html('25,00 ');
        $('#lblMonOurGar12').html('35,00 ');
        $('#lblMonOurGar13').html('45,00 ');

        //TABLA 2
        $('#lblTramo21').html('0 - 500 ');
        $('#lblTramo22').html('501 - 1,000 ');
        $('#lblTramo23').html('1,001 - 1,500 ');
        $('#lblTramo24').html('1,501 - 2,000 ');
        $('#lblTramo25').html('2,001 - 2,500 ');

        $('#lblMonOur21').html('55,00 ');
        $('#lblMonOur22').html('60,00 ');
        $('#lblMonOur23').html('90,00 ');
        $('#lblMonOur24').html('50,00 ');
        $('#lblMonOur25').html('100,00 ');

        $('#lblMonOurGar21').html('50,00 ');
        $('#lblMonOurGar22').html('80,00 ');
        $('#lblMonOurGar23').html('70,00 ');
        $('#lblMonOurGar24').html('80,00 ');
        $('#lblMonOurGar25').html('90,00 ');

        //TABLA 3
        $('#lblTramo31').html('0 - 500 ');
        $('#lblTramo32').html('501 - 1,000 ');
        $('#lblTramo33').html('1,001 - 1,500 ');
        $('#lblTramo34').html('1,501 - 2,000 ');

        $('#lblMonOur31').html('100,00 ');
        $('#lblMonOur32').html('195,00 ');
        $('#lblMonOur33').html('150,00 ');
        $('#lblMonOur34').html('10,00 ');

        $('#lblMonOurGar31').html('90,00 ');
        $('#lblMonOurGar32').html('95,00 ');
        $('#lblMonOurGar33').html('100,00 ');
        $('#lblMonOurGar34').html('105,00 ');
    }

    if ($("#cboTipoMoneda").val() == "2") { // Moneda Peso

        $('#lblTramo11').html('000.000 - 1.000.000 ');
        $('#lblTramo12').html('1.000.001 - 2.000.000 ');
        $('#lblTramo13').html('2.000.001 - 3.000.000 ');

        $('#lblMonOur11').html('20.250 ');
        $('#lblMonOur12').html('28.350 ');
        $('#lblMonOur13').html('36.450 ');

        $('#lblMonOurGar11').html('20.250 ');
        $('#lblMonOurGar12').html('28.350 ');
        $('#lblMonOurGar13').html('36.450 ');

        //TABLA 2
        $('#lblTramo21').html('000.000 - 1.000.000 ');
        $('#lblTramo22').html('1.000.001 - 2.000.000 ');
        $('#lblTramo23').html('2.000.001 - 3.000.000 ');
        $('#lblTramo24').html('3.000.001 - 4.000.000 ');
        $('#lblTramo25').html('4.000.001 - 5.000.000 ');

        $('#lblMonOur21').html('44.550 ');
        $('#lblMonOur22').html('48.600 ');
        $('#lblMonOur23').html('72.900 ');
        $('#lblMonOur24').html('40.500 ');
        $('#lblMonOur25').html('81.000 ');

        $('#lblMonOurGar21').html('40.500 ');
        $('#lblMonOurGar22').html('64.800 ');
        $('#lblMonOurGar23').html('56.700 ');
        $('#lblMonOurGar24').html('64.800 ');
        $('#lblMonOurGar25').html('72.900 ');

        //TABLA 3
        $('#lblTramo31').html('000.000 - 1.000.000 ');
        $('#lblTramo32').html('1.000.001 - 2.000.000 ');
        $('#lblTramo33').html('2.000.001 - 3.000.000 ');
        $('#lblTramo34').html('3.000.001 - 4.000.000 ');

        $('#lblMonOur31').html('81.000 ');
        $('#lblMonOur32').html('157.950 ');
        $('#lblMonOur33').html('121.500 ');
        $('#lblMonOur34').html('8.100 ');

        $('#lblMonOurGar31').html('72.900 ');
        $('#lblMonOurGar32').html('76.950 ');
        $('#lblMonOurGar33').html('81.000 ');
        $('#lblMonOurGar34').html('85.050 ');
    }
}